- radar.js
A sample TSV file that causes the error is attached
[2017_01.tsv.zip](https://github.com/zalando/tech-radar/files/671318/2017_01.tsv.zip)
> Fixed an issue where the radar failed to display due to an error when indexing the itemsByStage array

- .gitignore
- README.md
- package.json
I mainly added browserify for tinkering with this nice piece of radar.
> Add package.json for easier local development

- .zappr.yaml
> add zappr config file (#42)

- docs/index.html
- Publishes updated ring changes for Rust, Haskell, and Clojure.
- Cleans up the former HOLD entries to NIL.
> Updates Rust, Haskell, Clojure to HOLD

- docs/index.html
> Removes Google Analytics

- docs/index.html
- yarn.lock
Updated ring assignments and linked to Engineering Blog instead of an internal page.
> Tech Radar 06/2021

- docs/index.html
Sorting of the entries changed due to auto-generation.
> Tech Radar update 12/2021

- README.md
- docs/release/radar-0.6.js
Re #71. Adds `radar-0.6.js` with links for bullet points and highlights selected item in legend.
> release v0.6

- yarn.lock
> 2022-01-18 update dependencies

- docs/index.html
> Ring change update

- yarn.lock
Fix for CVE-2021-44906 (minimist)
> 2022-03-31 update dependencies

- yarn.lock
> 2022-05-07 update dependencies

- docs/index.html
Adds public Nakadi page as link for its entry instead of a private page.
> Uses public link for Nakadi

- docs/index.html
Before: 100 / 92 / 83 / 78
After: 100 / 100 / 92 / 100
> Fix lighthouse score for Tech Radar page

- MAINTAINERS
> Updates MAINTAINERS list

- yarn.lock
> dependencies update 2022-08-09

- docs/index.html
> Adds ring changes for 2022-08

- yarn.lock
Periodic dependency update. Supersedes #99.
> Dependencies update 2022-12-06

- docs/index.html
- docs/radar.js
Hey guys,
Thanks for your project. This is an awesome and clear tech stack visualization. We've [slightly modified it](https://github.com/qiwi/tech-radar) for our bloody enterprise purposes, and I'd like to suggest a pinch of our tweak ups:
1) Radar date on a new line
2) Bold accented groups headers
3) Colored ring labels
Before:
After:
> feat: radar style tweak ups

- README.md
- docs/index.html
After merging #75, I noticed that the default color palette has bad contrast. The new colors should offer a higher contrast ratio making the page more readable.
**Before**
**After**
> Adjusts color scheme for increased contrast of ring colors

- .npmrc
- package.json
- yarn.lock
Fixes warning for CVE-2022-25927
> Override ua-parser-js to 1.0.33

- package.json
- yarn.lock
Fixes CVE-2023-32695, CVE-2023-31125.
Closes #119 & closes #121
> dependencies update 2023-06-04

- .gitignore
- docs/radar.js
- package.json
- yarn.lock
Updates pinned versions of dev dependencies.
> Dependencies update 20230604

- package.json
- yarn.lock
> Dependencies update 20231029

- docs/config.json
Periodic update of ring assignment.
> Ring updates 20231031

- yarn.lock
> Dependencies update 20240109

- docs/config.json
- promote AWS Athena to TRIAL
- rename OpenTracing to OpenTelemetry
- move Redis to HOLD and instead introduce AWS ElastiCache in ADOPT and Valkey in ASSESS
> Tech Radar update 06/2024

- yarn.lock
> Dependencies update 2024-06-18

- README.md
- docs/config.json
- docs/radar.js
Follow-up to #150 from @SoumayaMauthoorMOJ
- Extends documentation in `README.md`
- Marks Valkey as new entry
- Applies formatting fixes to `radar.js`
> Uses and documents repo_url and new blips as stars

- .zappr.yaml
ComPR complains about non-existing team name. This PR uses an existing name.
> Use existing team name

- docs/radar.js
I made a few small changes:
- Made the position of the footer configurable
- I made the legend clearer by using a full circle
- I placed the optional table closer to the radar diagram
Link to html page showing updated full circle only: https://moj-analytical-services.github.io/tech-radar/
Link to hmtl page showing all changes: [moj-analytical-services.github.io/data-and-analytics-engineering-tech-radar/](https://moj-analytical-services.github.io/data-and-analytics-engineering-tech-radar/)
> Make footer configurable

- README.md
- docs/release/radar-0.9.js
- yarn.lock
New config parameters:
- font_family
- repo_url
- print_ring_descriptions_table
- footer_offset
Readme adjustments with screenshots demonstrating the config options to follow in separate PR.
> Release v0.9

- docs/radar.js
Hi,
I added 2 new parameter called `legend_offset` and `title_offset` to the config, to let developers customise legend and title offsets. As for PR #169 , this is an addition needed to resolve a problem we had on the [lastminute.com](https://corporate.lastminute.com) tech radar published on the official tech blog:
[https://technology.lastminute.com/tech-radar-2024-10/](https://technology.lastminute.com/tech-radar-2024-10/)
Thanks for the library, we hope this contribution can be helpful to the community 🙏.
> Legend and title offset configurable - parameter + default value

- docs/release/radar-0.10.js
New configuration parameters:
- `legend_column_width`: allowing to increase width of legend columns to make space for longer technology names (#169 by @chicio)
- `legend_offset`: allowing to move legend further away from the radar to accommodate for longer technology names (#170 by @chicio)
- `title_offset`: allowing to align title with legend (#170 by @chicio)
Usage example in #169. Config in [comment](https://github.com/zalando/tech-radar/pull/169#issuecomment-2492608144).
> Release 0.10

- yarn.lock
> Dependencies update 2025-01-09

- README.md
> Update footer to 2025

- docs/config.json
> Updated ring assignments

- docs/config.json
Removes Exasol from the Tech Radar
> remove exasol

- docs/config.json
> 2025-05 rings update
