docs/radar.js

This PR adds highlighting of the legend item and showing the bubble when there's hovered on either the legend item or the blip in the radar.
Similar to the behavour of the [Thought Works tech radar](https://www.thoughtworks.com/radar/techniques).

Add highlighting of legend item and show bubble on hover

---

README.md

Adds a comment prefix on a cosmetic line that was breaking the code when copy-pasted.
Also removes an extra blank space.

Fix copy-paste example on readme

---

docs/index.html
yarn.lock

* Elm: ASSESS ⟶ HOLD: Elm was tried and did not pick up momentum in Zalando. The community in Zalando is non-existent.
* KairosDB: TRIAL ⟶ NIL: Not widely used. In recent years, only a handful of projects have used it, so hard to recommend outright. The project itself is not hugely active, relies on two individuals. There's no Kubernetes support for it. Time-series systems have developed as a category and it may be worth assessing other options.

update: Elm -> HOLD, KairosDB -> NIL

---

docs/radar.js

Firefox requires that the units be added for font sizes in svgs

Fix font issues with firefox

---

docs/index.html
docs/radar.js

Use standard `href` attribute to support links for entries (legend) and update Zalando links to something meaningful.
Replaces #63.

Add links for technology entries.

---

docs/index.html

Current link leads to error page instead of https://engineering.zalando.com/tags/apache-kafka.html

Fix Kafka link

---

package.json
yarn.lock

Supersedes #81. Also addresses CVE-2020-36048 in engine.io by pinning version for socket.io
```
browser-sync@2.27.7 requires engine.io@~3.5.0 via a transitive dependency on socket.io@2.4.0
```

2022-02-15 update dependencies

---

package.json
yarn.lock

override portscanner to 2.2.0, which uses newer async. Currently, browser-sync@2.27.9 requires async@1.5.2 via portscanner@2.1.1

Fix CVE-2021-43138

---

package.json
yarn.lock

Fix CVE-2022-24999. Overrides qs to 6.2.4 until browser-sync upgrades its dependencies.

Pins qs to version 6.2.4

---

README.md
docs/index.html
docs/radar.js

Includes changes from #73.
1. Links are now always enabled for blips
Previously, it was only enabled for blips if there is
no legend (config.print_layout = true)
2. Use xlink:href everywhere
Previously, blips used xlink:href, but text still used href.
xlink:href has actually been deprecated, but currently still
has better cross-platform support.
3. Links can now open in new tabs
Previously, links always opened in the existing tab.  This adds
a new config: links_in_new_tabs.  Setting that to true will
add a target="_blank" for all hrefs, causing the link to be
opened in a new tab.  Setting config.links_in_new_tabs to false
or not including it at all retains the old behavior.

Enables links for blips. Makes link target configurable.

---

docs/radar.js

By increasing the margin between columns we can avoid overlapping text.
When one of the lengthier items moves to 1st column, most likely support for multi-line text will be required.

Adds more space in legend to avoid overlapping entries

---

docs/index.html

Just a small typo fix for the Docker technology URL.

fix: typo in docker technology url

---

package.json
yarn.lock

htmllint binary is included in the package "htmllint-cli" and not "htmllint" so to be able to run "yarn lint" the cli package needs to be included".

Fix htmllint-cli dependency

---

README.md

Organizations should be encouraged to have their own Tech Radar by being guided how to start & deploy. They also may have concerns to make it public, so having a quick guideline will help them to solve any concerns that are preventing them to use Tech Radar.

Add guideline for deploying cloudflare pages

---

.eslintrc.json
package.json
yarn.lock

htmllint-cli is not updated since 6y+. Removal reduces the total number of packages imported by ~45%.

Replaces htmllint-cli with eslint-plugin-html

---

package.json
yarn.lock

removes dependency on localtunnel which is unmaintained, see https://github.com/BrowserSync/browser-sync/releases/tag/v3.0.1

update browser-sync to 3.0.2

---

docs/radar.js

It will be good to support config.scale option for small size radar.
It produces 700/500 size radar from 1400/1000.
``` javascript
radar_visualization({
svg_id: "radar",
width: 1400,
height: 1000,
scale: 0.5,   ;; <<----
```

add: config.scale option

---

README.md
docs/radar.js

Currently the radar SVG has its font-family hardcoded, with this PR it becomes customizable. 
I noticed that `radar.css` prefers Source Sans Pro for the surrounding text. Let me know if I should also adjust that or you'd like to handle it separately.

Allow customization of font-family

---

docs/index.html
docs/radar.css
docs/radar.js

Hello @bocytko I really like this visualisation and would like to propose a few backwards-compatible changes:
- Move various config variables to `radar.js` and set default values to simplify `index.html` but allow users to overwrite values
- Link radar title to repository homepage if provided, otherwise stay on the same page
- Show blip as star if `moved = null` indicating that it is new
- Update footer text and place beneath radar diagram
- Include optional table of ring assignments and descriptions
Here is what my radar looks like with these changes: https://moj-analytical-services.github.io/data-and-analytics-engineering-tech-radar/

Show new blips as stars and add table of ring descriptions

---

docs/radar.js

`false || true` yields `true`. This was not correctly considered in the config handling introduced in #150.
The updated code checks explicitly for `undefined` properties.

Fixed handling of defaults for boolean config properties

---

README.md

This should suggest the https link otherwise this fails in https-only environments like Github Pages.

Fix link to radar.js release

---

docs/radar.js

Hi,
I added a new parameter called `legend_column_width` to the config. This parameter gives to the developers the ability to customise the legends column width. This is an addition needed to resolve a problem we had on the [lastminute.com](https://corporate.lastminute.com) tech radar published on the official tech blog:
[https://technology.lastminute.com/tech-radar-2024-10/](https://technology.lastminute.com/tech-radar-2024-10/)
The default width (used in the translation transform) is 140. See attached screenshots for an example before and after fix (increased column width (and so translation on x) of 160 pixels).
Thanks for the library, we hope this contribution can be helpful to the community 🙏.

Legends column width configurable - parameter + default value

---

docs/config.json
docs/radar.js

Hi,
as discussed in #169,I tried to add multiline support for legend items with long names. I used `tspan` as discussed and some dynamic height calculations (based  on the bounding box (`getBBox`) + `getComputedTextLength`).
It works as expected. The items lines are aligned after the legend number.
There is still room for improvement, because we should be able to calculate the entire structure of the legends dynamically. Anyway for now, if a legend list of items is too long we should play with the parameters I added the previous PRs to fix the offset (in particular the legends offsets).
Attached you can find some example:
* the Zalando tech radar rendered, where we have an example of an item going on 2 lines
* the a video + a zip containing a working example of the Lastminute tech radar …

Multiline legend items

---

README.md

Also, link to the PR so that users quickly see what changes they have to apply in their forks.

Add callout for d3.js v7 being used since 0.12 release
